version: "3.7"
services:
  web-server:
    build:
      dockerfile: docker/php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./:/var/www/"
    ports:
      - "80:80"
    stdin_open: true # docker run -i
    tty: true 
  mysql-server:
    image: mysql:8.0.19
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
volumes:
  mysql-data: